# gem-codesearch.dev.ruby-lang.org: full-text search over the latest version
# of every gem on rubygems.org, via https://github.com/akr/gem-codesearch.
# Committers ssh in and run /usr/local/bin/gem-codesearch; a daily cron job
# refreshes the rubygems mirror, the unpacked tree in /srv/gems and the
# csearch indexes.

include_recipe "setup-users"

package 'git'
package 'ruby'
package 'rake'
# Google codesearch: provides /usr/bin/cindex and /usr/bin/csearch, which the
# Rakefile's index_csearch task and bin/gem-codesearch drive.
package 'codesearch'

# `gem mirror` used by the Rakefile's mirror task. Installed system-wide for
# the Ubuntu ruby package (/var/lib/gems).
gem_package 'rubygems-mirror'

user 'gem-codesearch' do
  shell '/bin/bash'
end

home = '/home/gem-codesearch'
checkout = "#{home}/gem-codesearch"

directory home do
  mode '755'
  owner 'gem-codesearch'
end

# The unpacked corpus lives on the dedicated 300G /srv volume; the root
# volume is too small for it. Must stay world-readable so committers can
# open the hit files reported by gem-codesearch.
directory '/srv/gems' do
  mode '755'
  owner 'gem-codesearch'
end

# Same workaround as default.rb: mitamae's git resource cannot update a repo
# whose HEAD was moved off the deploy branch (e.g. by a manual `git checkout
# master`); drop the stale deploy branch beforehand.
execute "remove stale deploy branch in #{checkout}" do
  command "git -C #{checkout} branch -D deploy"
  user 'gem-codesearch'
  only_if "test \"$(git -C #{checkout} rev-parse --abbrev-ref HEAD)\" != deploy && git -C #{checkout} rev-parse -q --verify refs/heads/deploy"
end

# No `revision` on purpose: mitamae then fetches origin and resolves the
# remote HEAD on every apply, so each hocho run re-pins the checkout to the
# upstream master head (the deploy branch). The mirror/, csearchindexes/ and
# log/ working data live untracked inside the checkout and survive this.
git checkout do
  repository 'https://github.com/akr/gem-codesearch.git'
  user 'gem-codesearch'
end

# Search entry point for committers (ssh ... gem-codesearch PATTERN). The
# implementation is bin/gem-codesearch in the checkout, so it follows
# upstream master; only the site-specific paths live here.
file '/usr/local/bin/gem-codesearch' do
  mode '755'
  content <<-EOF
#!/bin/sh
export GEM_CODESEARCH_DIR=#{checkout}
export GEM_CODESEARCH_GEM_DIR=/srv/gems
exec #{checkout}/bin/gem-codesearch "$@"
  EOF
end

directory "#{home}/cron-logs" do
  mode '755'
  owner 'gem-codesearch'
end

# Daily refresh. RUBYGEMS_MIRROR_ONLY_LATEST keeps the mirror to the newest
# version of each gem; the full mirror would not fit on /srv. HOME is set
# because `gem mirror` reads $HOME/.gem/.mirrorrc (generated by the
# Rakefile). The trailing chmod keeps the freshly unpacked gems readable for
# committers' searches.
file "#{home}/cron-run.sh" do
  mode '755'
  owner 'gem-codesearch'
  content <<-EOF
#!/bin/bash
export HOME=#{home}
cd #{checkout} || exit 1
LOG=#{home}/cron-logs/$(date +%Y%m%d%H%M%S).log
RUBYGEMS_MIRROR_ONLY_LATEST=TRUE GEM_CODESEARCH_GEM_DIR=/srv/gems rake mirror unpack index_csearch >& "$LOG"
chmod -R o+r /srv/gems
  EOF
end

crontab_path = "#{home}/.crontab"

# NOTE: no <<~ heredoc here; the mruby in mitamae <= 1.11 misparses it (see
# chkbuild-cron.rb).
file crontab_path do
  owner 'gem-codesearch'
  mode '600'
  content [
    'MAILTO=""',
    "0 15 * * * #{home}/cron-run.sh",
    '',
  ].join("\n")
end

execute "crontab -u gem-codesearch #{crontab_path}" do
  not_if "crontab -l -u gem-codesearch 2>/dev/null | cmp -s - #{crontab_path}"
end
