debian10.rubyci.org: &default
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

funtoo.rubyci.org:
  <<: *default

amazon.rubyci.org:
  <<: *default

amazon2.rubyci.org:
  <<: *default

opensuseleap.rubyci.org:
  <<: *default

arch.rubyci.org:
  <<: *default

icc.rubyci.org:
  <<: *default

freebsd12.rubyci.org:
  <<: *default

fedora31.rubyci.org:
  <<: *default

fedora32.rubyci.org:
  <<: *default

centos6.rubyci.org:
  <<: *default

centos7.rubyci.org:
  <<: *default

centos8.rubyci.org:
  <<: *default

rhel8.rubyci.org:
  <<: *default

debian9.rubyci.org:
  <<: *default

debian10.rubyci.org:
  <<: *default

debian.rubyci.org:
  <<: *default

openbsd.rubyci.org:
  <<: *default

ubuntu1604.rubyci.org:
  <<: *default

ubuntu1804.rubyci.org:
  <<: *default

ubuntu2004.rubyci.org:
  <<: *default

ubuntu.rubyci.org:
  <<: *default

riscv.rubyci.org:
  <<: *default

graviton2.rubyci.org:
  <<: *default

ppc64le.rubyci.org: # power9
  <<: *default

s390x.rubyci.org: # z15
  <<: *default
