debian.rubyci.org: &default
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

amazon2.rubyci.org:
  <<: *default

opensuseleap.rubyci.org:
  <<: *default

arch.rubyci.org:
  <<: *default

icc.rubyci.org:
  <<: *default

rhel8.rubyci.org:
  <<: *default

debian11.rubyci.org:
  <<: *default

openbsd.rubyci.org:
  <<: *default

ubuntu2004.rubyci.org:
  <<: *default

ubuntu.rubyci.org:
  <<: *default

riscv.rubyci.org:
  <<: *default

ppc64le.rubyci.org: # power9
  <<: *default

s390x.rubyci.org: # z15
  <<: *default

freebsd13.rubyci.org:
  <<: *default

gem-codesearch.dev.ruby-lang.org:
  <<: *default

ubuntu2204.rubyci.org:
  <<: *default

ubuntu2404.rubyci.org:
  <<: *default

crossruby.rubyci.org:
  <<: *default

rhel9.rubyci.org:
  <<: *default

amazon2023.rubyci.org:
  <<: *default

debian12.rubyci.org:
  <<: *default

freebsd14.rubyci.org:
  <<: *default

fedora40-arm.rubyci.org:
  <<: *default

fedora41.rubyci.org:
  <<: *default

ubuntu-arm.rubyci.org:
  <<: *default
