debian.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

amazon2.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

opensuseleap.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

arch.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

icc.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

rhel8.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

debian11.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

openbsd.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

ubuntu.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

riscv.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

ppc64le.rubyci.org: # power9
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

s390x.rubyci.org: # z15
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

freebsd13.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

gem-codesearch.dev.ruby-lang.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

ubuntu2204.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

ubuntu2404.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

crossruby.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

rhel9.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

amazon2023.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

debian12.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

freebsd14.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

fedora41.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

fedora42-arm.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

ubuntu-arm.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

debian13.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb

rhel10.rubyci.org:
  properties:
    nopasswd_sudo: true
    compress: false
    run_list:
      - recipes/default.rb
