// generated by get-zones. This is 'a decent first draft' and requires editing.

var DSP_CLOUDFLARE = NewDnsProvider("cloudflare", "CLOUDFLAREAPI");
var REG_CHANGEME = NewRegistrar("none");

D("rubyci.org", REG_CHANGEME,
	DnsProvider(DSP_CLOUDFLARE),
	DefaultTTL(1),
	A("amazon2023", "35.72.97.116"),
	A("amazon2", "54.250.87.137"),
	A("arch", "35.72.171.27"),
	A("arm64-neoverse-n1", "145.40.77.87"),
	A("centos7", "54.249.203.108"),
	A("crossruby", "54.65.185.15"),
	A("debian11", "54.178.164.239"),
	A("debian12", "18.177.243.215"),
	A("debian13", "35.72.238.43"),
	A("debian", "35.73.95.28"),
	A("fedora42-arm", "54.249.203.108"),
	A("fedora43", "54.249.168.246"),
	A("freebsd13", "18.176.170.223"),
	A("freebsd14", "35.73.133.12"),
	A("freebsd15-arm", "52.196.12.20"),
	A("icc", "18.180.104.156"),
	A("openbsd", "52.197.61.51"),
	A("opensuseleap", "3.113.91.40"),
	A("ppc64le", "140.211.168.162"),
	A("rhel10", "35.76.91.191"),
	A("rhel8", "35.73.137.17"),
	A("rhel9", "18.177.224.191"),
	A("riscv", "18.181.4.174"),
	A("s390x", "148.100.84.245"),
	A("solaris", "133.162.73.61"),
	A("ubuntu2004-arm", "54.249.168.246"),
	A("ubuntu2004", "52.196.12.20"),
	A("ubuntu2204", "54.248.215.194"),
	A("ubuntu2404", "18.180.242.9"),
	A("ubuntu-arm", "18.178.229.119"),
	A("ubuntu", "35.72.236.42"),
	// Cloudflare flattens this apex CNAME; dnscontrol expresses it as ALIAS.
	ALIAS("@", "rubyci.org.herokudns.com."),
	CNAME("www", "www.rubyci.org.herokudns.com."),
);

